# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\pythonWorkSpace\flight-control\project\demo\PyQt5\Button&TextTest\Button&TextTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import asyncio
import threading
from ssl import SSLEOFError
from time import sleep
from PyQt5 import QtCore, QtGui, QtWidgets
from torch import celu


class Ui_MainWindow(object):
    LabelText = "null"
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 180, 100, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.button_func)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 240, 100, 12))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 290, 241, 91))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", self.LabelText))

    def button_func(self):
        button_thread = threading.Thread(target=self.button_func_thread)
        button_thread.start()
        # print("loop begin")
        # loop = asyncio.get_event_loop()
        # tasks = [self.check01(), self.check02(), self.check03()]
        # loop.run_until_complete(asyncio.wait(tasks))
        # loop.close
        # print("loop finished")

    def button_func_thread(self):
        print("loop begin")
        loop = asyncio.new_event_loop()
        tasks = [self.check01(), self.check02(), self.check03()]
        loop.run_until_complete(asyncio.wait(tasks))
        loop.close
        print("loop finished")

    async def check01(self):
        # print("010 checked")
        await asyncio.sleep(1)
        self.LabelText = '01 checked'
        # print("011 checked")
        self.label.setText(self.LabelText)
        # print("012 checked")
    
    async def check02(self):
        # print("020 checked")
        await asyncio.sleep(3)
        self.LabelText = '02 checked'
        # print("021 checked")
        self.label.setText(self.LabelText)
        # print("022 checked")
        # await asyncio.sleep(2)
        # print('023 checked')

    async def check03(self):
        # print("030 checked")
        await asyncio.sleep(2)
        self.LabelText = '03 checked'
        # print("031 checked")
        self.label.setText(self.LabelText)
        # print("032 checked")
