from mavsdk.mission import*


def get_scout_missions(tar_pos):
    scout_mission = [MissionItem(tar_pos[0][0],
                                tar_pos[0][1],
                                15,
                                10,
                                True,
                                float('nan'),
                                float('nan'),
                                MissionItem.CameraAction.NONE,
                                float('nan'),
                                float('nan'),
                                float('nan'),
                                float('nan'),
                                float('nan')),
                    MissionItem(tar_pos[1][0],
                                tar_pos[1][1],
                                15,
                                10,
                                True,
                                float('nan'),
                                float('nan'),
                                MissionItem.CameraAction.NONE,
                                float('nan'),
                                float('nan'),
                                float('nan'),
                                float('nan'),
                                float('nan')),
                    MissionItem(tar_pos[2][0],
                                tar_pos[2][1],
                                15,
                                10,
                                True,
                                float('nan'),
                                float('nan'),
                                MissionItem.CameraAction.NONE,
                                float('nan'),
                                float('nan'),
                                float('nan'),
                                float('nan'),
                                float('nan'))]
    return  scout_mission

def get_bomb_mission(tar_pos):
    bomb1 = [MissionItem(tar_pos[0][0],
                    tar_pos[0][1],
                    15,
                    10,
                    True,
                    float('nan'),
                    float('nan'),
                    MissionItem.CameraAction.NONE,
                    float('nan'),
                    float('nan'),
                    float('nan'),
                    float('nan'),
                    float('nan'))]

    # 设置打击任务2
    bomb2 = [MissionItem(tar_pos[1][0],
                        tar_pos[1][1],
                        15,
                        10,
                        True,
                        float('nan'),
                        float('nan'),
                        MissionItem.CameraAction.NONE,
                        float('nan'),
                        float('nan'),
                        float('nan'),
                        float('nan'),
                        float('nan'))]

    # 设置打击任务3
    bomb3 = [MissionItem(tar_pos[2][0],
                        tar_pos[2][1],
                        15,
                        10,
                        True,
                        float('nan'),
                        float('nan'),
                        MissionItem.CameraAction.NONE,
                        float('nan'),
                        float('nan'),
                        float('nan'),
                        float('nan'),
                        float('nan'))]
    return [bomb1, bomb2, bomb3]